version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Umartahir93/learning-go-with-test"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"
enabled = true