version = 1
test_patterns = [
    "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
dependencies_vendored = false
cgo_enabled = false
import_root = "github.com/umartahir93/learning-go-with-test"
